options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_32

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/rainbow-data-production-483609/rainbow-docker-repo/risingwave:$TAG_NAME'
      - './docker/Dockerfile'
      - '--build-arg'
      - 'CARGO_PROFILE=production'

images:
  - 'gcr.io/rainbow-data-production-483609/rainbow-docker-repo/risingwave:$TAG_NAME'
